**THIS IS THE 2009-2010 CLEANING**

**import all libraries**

In [1]:
import pandas as pd
import numpy as np

**LOAD THE CSV**

In [2]:
df = pd.read_excel("../data/online_retail_II.xlsx",sheet_name="Year 2009-2010")

**display the csv**

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

**csv info**

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 38.8+ MB

**columns in list**

In [5]:
object_cols = ["Invoice","StockCode","Description"]

**fixing df types**

In [6]:
df[object_cols] = df[object_cols].astype("string")

**turning column names to lowercase and removing spacing**

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","",regex=False)

**turning column values to lower case**

In [8]:
col_str = ["description","country","stockcode"]

df[col_str] = df[col_str].apply(lambda x:x.str.lower())
df[col_str] = df[col_str].apply(lambda x:x.str.strip())

**working on the time column seperating them into its own column**

In [9]:
df["year"] = df["invoicedate"].dt.year
df["month"] = df["invoicedate"].dt.month_name()
df["day"] = df["invoicedate"].dt.day_name()
# df["time"] = df["invoicedate"].dt.time

df["hour"] = df["invoicedate"].dt.hour

**adding new columns**

In [10]:
df["returned"] = np.where(df["quantity"] < 0,"yes","no")

df["gross_sales"] = np.where(df["quantity"] < 0,0,
                             df["quantity"] * df["price"])

df["net_sales"] = df["quantity"] * df["price"]

**viewing final df**

In [11]:
df.head()

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales
0,489434,85048,15cm christmas glass ball 20 lights,12,2009-12-01 07:45:00,6.95,13085.0,united kingdom,2009,December,Tuesday,7,no,83.4,83.4
1,489434,79323p,pink cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0
2,489434,79323w,white cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0
3,489434,22041,"record frame 7"" single size",48,2009-12-01 07:45:00,2.10,13085.0,united kingdom,2009,December,Tuesday,7,no,100.8,100.8
4,489434,21232,strawberry ceramic trinket box,24,2009-12-01 07:45:00,1.25,13085.0,united kingdom,2009,December,Tuesday,7,no,30.0,30.0

**viewing info**

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      525461 non-null  string
 1   stockcode    525461 non-null  string
 2   description  522533 non-null  string
 3   quantity     525461 non-null  int64
 4   invoicedate  525461 non-null  datetime64[us]
 5   price        525461 non-null  float64
 6   customerid   417534 non-null  float64
 7   country      525461 non-null  str
 8   year         525461 non-null  int32
 9   month        525461 non-null  str
 10  day          525461 non-null  str
 11  hour         525461 non-null  int32
 12  returned     525461 non-null  str
 13  gross_sales  525461 non-null  float64
 14  net_sales    525461 non-null  float64
dtypes: datetime64[us](1), float64(4), int32(2), int64(1), str(4), string(3)
memory usage: 89.7 MB

**investigation**

In [13]:
check = df.iloc[df["quantity"] < 1]
check

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales
178,C489449,22087,paper bunting white lace,-12,2009-12-01 10:33:00,2.95,16321.0,australia,2009,December,Tuesday,10,yes,0.0,-35.40
179,C489449,85206a,cream felt easter egg basket,-6,2009-12-01 10:33:00,1.65,16321.0,australia,2009,December,Tuesday,10,yes,0.0,-9.90
180,C489449,21895,potting shed sow 'n' grow set,-4,2009-12-01 10:33:00,4.25,16321.0,australia,2009,December,Tuesday,10,yes,0.0,-17.00
181,C489449,21896,potting shed twine,-6,2009-12-01 10:33:00,2.10,16321.0,australia,2009,December,Tuesday,10,yes,0.0,-12.60
182,C489449,22083,paper chain kit retro spot,-12,2009-12-01 10:33:00,2.95,16321.0,australia,2009,December,Tuesday,10,yes,0.0,-35.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525231,538159,21324,<NA>,-18,2010-12-09 17:17:00,0.00,NaN,united kingdom,2010,December,Thursday,17,yes,0.0,-0.00
525232,538158,20892,<NA>,-32,2010-12-09 17:17:00,0.00,NaN,united kingdom,2010,December,Thursday,17,yes,0.0,-0.00
525234,538161,46000s,dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,united kingdom,2010,December,Thursday,17,yes,0.0,-0.00
525235,538162,46000m,dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,united kingdom,2010,December,Thursday,17,yes,0.0,-0.00
525282,C538164,35004b,set of 3 black flying ducks,-1,2010-12-09 17:32:00,1.95,14031.0,united kingdom,2010,December,Thursday,17,yes,0.0,-1.95

In [14]:
df["description"].unique()

<ArrowStringArray>
['15cm christmas glass ball 20 lights',                  'pink cherry lights',
                 'white cherry lights',         'record frame 7" single size',
      'strawberry ceramic trinket box',           'pink doughnut trinket pot',
                 'save the planet mug',  'fancy font home sweet home doormat',
                            'cat bowl',      'dog bowl , chasing ball design',
 ...
   'baking mould heart milk chocolate',  'baking mould heart white chocolate',
   'baking mould toffee cup chocolate',     'baking mould chocolate cupcakes',
   'baking mould rose white chocolate',    'baking mould rose milk chocolate',
    'baking mould chocolate cup cakes',   'baking mould easter egg milk choc',
               '*boombox ipod classic',                              'faulty']
Length: 4634, dtype: string

In [15]:
gross_sales = df["gross_sales"].sum().round(2)
net_sales = df["net_sales"].sum().round(2)
print(gross_sales)
print(net_sales)

10169713.57
9539484.63

In [16]:
df["country"].unique()

<ArrowStringArray>
[      'united kingdom',               'france',                  'usa',
              'belgium',            'australia',                 'eire',
              'germany',             'portugal',                'japan',
              'denmark',              'nigeria',          'netherlands',
               'poland',                'spain',      'channel islands',
                'italy',               'cyprus',               'greece',
               'norway',              'austria',               'sweden',
 'united arab emirates',              'finland',          'switzerland',
          'unspecified',                'malta',              'bahrain',
                  'rsa',              'bermuda',            'hong kong',
            'singapore',             'thailand',               'israel',
            'lithuania',          'west indies',              'lebanon',
                'korea',               'brazil',               'canada',
              'iceland']
Length: 40, dtype: str

In [17]:
df.to_parquet("../data/cleaned_2009_2010.parquet")