**THIS IS THE 2010-2011 CLEANING**

**import all libraries**

In [2]:
import pandas as pd
import numpy as np

**LOAD THE CSV**

In [3]:
df = pd.read_excel("../data/online_retail_II.xlsx",sheet_name="Year 2010-2011")

**display the csv**

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

**csv info**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 40.0+ MB

**columns in list**

In [6]:
object_cols = ["Invoice","StockCode","Description"]

**fixing df types**

In [7]:
df[object_cols] = df[object_cols].astype("string")

**turning column names to lowercase**

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","",regex=False)

**turning column values to lower case**

In [9]:
col_str = ["description","country"]

df[col_str] = df[col_str].apply(lambda x:x.str.lower())
df.columns = df.columns.str.replace(" ","",regex=False)

**turning column values to lower case**

In [10]:
col_str = ["description","country","stockcode"]

df[col_str] = df[col_str].apply(lambda x:x.str.lower())
df[col_str] = df[col_str].apply(lambda x:x.str.strip())

**working on the time column seperating them into its own column**

In [11]:
df["year"] = df["invoicedate"].dt.year
df["month"] = df["invoicedate"].dt.month_name()
df["day"] = df["invoicedate"].dt.day_name()
# df["time"] = df["invoicedate"].dt.time

df["hour"] = df["invoicedate"].dt.hour

**adding new columns**

In [12]:
df["returned"] = np.where(df["quantity"] < 0,"yes","no")

df["gross_sales"] = np.where(df["quantity"] < 0,0,
                             df["quantity"] * df["price"])

df["net_sales"] = df["quantity"] * df["price"]

**viewing final df**

In [13]:
df.head()

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales
0,536365,85123a,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850.0,united kingdom,2010,December,Wednesday,8,no,15.30,15.30
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom,2010,December,Wednesday,8,no,20.34,20.34
2,536365,84406b,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850.0,united kingdom,2010,December,Wednesday,8,no,22.00,22.00
3,536365,84029g,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom,2010,December,Wednesday,8,no,20.34,20.34
4,536365,84029e,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850.0,united kingdom,2010,December,Wednesday,8,no,20.34,20.34

**viewing info**

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      541910 non-null  string
 1   stockcode    541910 non-null  string
 2   description  540456 non-null  string
 3   quantity     541910 non-null  int64
 4   invoicedate  541910 non-null  datetime64[us]
 5   price        541910 non-null  float64
 6   customerid   406830 non-null  float64
 7   country      541910 non-null  str
 8   year         541910 non-null  int32
 9   month        541910 non-null  str
 10  day          541910 non-null  str
 11  hour         541910 non-null  int32
 12  returned     541910 non-null  str
 13  gross_sales  541910 non-null  float64
 14  net_sales    541910 non-null  float64
dtypes: datetime64[us](1), float64(4), int32(2), int64(1), str(4), string(3)
memory usage: 92.4 MB

In [15]:
df.to_parquet("../data/cleaned_2010_2011.parquet")