**import libraries**

In [19]:
import pandas as pd

**load all dataframes**

In [20]:
df_2009_2010 = pd.read_parquet("../data/cleaned_2009_2010.parquet")
df_2010_2011 = pd.read_parquet("../data/cleaned_2010_2011.parquet")

**combined by concatination**

In [21]:
overlap = (df_2009_2010["year"] == 2010) & (df_2009_2010["month"] == "December")

df_all = pd.concat(
    [df_2009_2010[~overlap], df_2010_2011],
    ignore_index=True
)

In [22]:
df_all.head()

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales
0,489434,85048,15cm christmas glass ball 20 lights,12,2009-12-01 07:45:00,6.95,13085.0,united kingdom,2009,December,Tuesday,7,no,83.4,83.4
1,489434,79323p,pink cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0
2,489434,79323w,white cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0
3,489434,22041,"record frame 7"" single size",48,2009-12-01 07:45:00,2.10,13085.0,united kingdom,2009,December,Tuesday,7,no,100.8,100.8
4,489434,21232,strawberry ceramic trinket box,24,2009-12-01 07:45:00,1.25,13085.0,united kingdom,2009,December,Tuesday,7,no,30.0,30.0

In [23]:
# December 2010 should now appear once, from the second file only
dec_2010 = df_all[(df_all["year"] == 2010) & (df_all["month"] == "December")]
print(dec_2010["net_sales"].sum())

# compare with the second file alone, these should match
print(df_2010_2011[(df_2010_2011["year"] == 2010) & (df_2010_2011["month"] == "December")]["net_sales"].sum())

748957.02
748957.02

In [24]:
df_all["description"].unique().tolist()

['15cm christmas glass ball 20 lights',
 'pink cherry lights',
 'white cherry lights',
 'record frame 7" single size',
 'strawberry ceramic trinket box',
 'pink doughnut trinket pot',
 'save the planet mug',
 'fancy font home sweet home doormat',
 'cat bowl',
 'dog bowl , chasing ball design',
 'heart measuring spoons large',
 'lunchbox with cutlery fairy cakes',
 'door mat black flock',
 'love building block word',
 'home building block word',
 'assorted colour bird ornament',
 'peace wooden block letters',
 'christmas craft white fairy',
 'heart ivory trellis large',
 'heart filigree dove large',
 'full english breakfast plate',
 'pizza plate in box',
 'black diner wall clock',
 'set of 3 black flying ducks',
 'area patrolled metal sign',
 'please one person  metal sign',
 'bath building block word',
 'classic white frame',
 'small marshmallows pink bowl',
 'biscuits small bowl light blue',
 'scottie dog hot water bottle',
 'christmas craft heart decorations',
 'christmas craft heart stocking',
 'party cone christmas decoration',
 'peace small wood letters',
 'joy large wood letters',
 'cinammon & orange wreath',
 'eucalyptus & pinecone  wreath',
 'wooden box advent calendar',
 'floral blue monster',
 'retro coffee mugs assorted',
 'inflatable political globe',
 'stripes design monkey doll',
 'blue padded soft mobile',
 'pack of 6 skull paper cups',
 'pack of 20 skull paper napkins',
 'hanging heart zinc t-light holder',
 'pink blue felt craft trinket box',
 'feltcraft doll rosie',
 'feltcraft doll maria',
 'feltcraft doll emily',
 'vintage snakes & ladders',
 'chocolate hot water bottle',
 'dinosaurs  writing set',
 'set of meadow  flower stickers',
 'charlie and lola charlotte bag',
 'jumbo bag charlie and lola toys',
 'jumbo bag toys',
 'country cottage  doorstop green',
 'gingham heart  doorstop red',
 'charlie+lola red hot water bottle',
 'charlie lola blue hot water bottle',
 'charlie+lola pink hot water bottle',
 'charlie + lola red hot water bottle',
 'tomato charlie+lola coaster set',
 'carrot charlie+lola coaster set',
 'charlie + lola biscuits tins',
 'charlie and lola figures tins',
 'charlie & lola wastepaper bin blue',
 'charlie & lola wastepaper bin flora',
 'christmas pudding trinket pot',
 'baking set 9 piece retrospot',
 'retro spot tea set ceramic 11 pc',
 'lunchbox with cutlery retrospot',
 'black/blue dots ruffled umbrella',
 'red/white dots ruffled umbrella',
 'wrap english rose',
 'wrap blue russian folkart',
 'set of three vintage gift wraps',
 'retro sport party bag + sticker set',
 'assorted cakes fridge magnets',
 'vintage design gift tags',
 'red toadstool led night light',
 'set/3 russian doll stacking tins',
 'pack 20 dolly pegs',
 'assorted colour mini cases',
 'postage',
 'bird decoration red spot',
 'red woolly hottie white heart.',
 'union jack guns & roses  doormat',
 'yellow + brown bear felt purse kit',
 'white hanging heart t-light holder',
 'kings choice small tube matches',
 'kings choice giant tube matches',
 'kings choice cigar box matches',
 'empire tissue box',
 'greeting card, the black cat',
 'rainy ladies birthday card',
 'banquet birthday  card',
 'space boy birthday card',
 'ring of roses birthday card',
 'botanical lavender birthday card',
 'set3 book box green gingham flower',
 'set/3 red gingham rose storage box',
 'set 12 retro white chalk sticks',
 'vintage snap cards',
 'bingo set',
 'victorian sewing kit',
 'retro red spotty washing up gloves',
 'set/2 red spotty tea towels',
 'vinyl record frame silver',
 'bathroom metal sign',
 'ladies & gentlemen metal sign',
 'red spotty oven glove double',
 'pink felt hanging heart w flower',
 'blue felt hanging heart w flower',
 'retro spot lamp',
 'party cones candy assorted',
 'heart string memo holder hanging',
 'folkart bauble christmas decoration',
 '6 crochet strawberries',
 'set of 72 pink heart paper doilies',
 'lovebird hanging decoration white',
 'white tall porcelain t-light holder',
 'edwardian toilet roll unit',
 'set/6 strawberry paper cups',
 'set/6 woodland paper cups',
 'jumbo bag pink vintage paisley',
 'garland , wooden  " happy easter"',
 'set/6 woodland paper plates',
 'red hanging heart t-light holder',
 'victorian glass hanging t-light',
 'union jack hot water bottle',
 'red spot ceramic drawer knob',
 "paper chain kit 50's christmas",
 'heart filigree dove  small',
 'frying pan red polkadot',
 'paper chain kit retro spot',
 'hot water bottle tea and sympathy',
 'red spot heart hot water bottle',
 'jumbo bag scandinavian paisley',
 'jumbo bag red white spotty',
 'charlotte bag , pink/white spots',
 'red spotty charlotte bag',
 'retro spot  cigar box matches',
 'lunch bag red spotty',
 'lunch bag cars blue',
 'lunch bag woodland',
 'red spotty round cake tins',
 'large heart measuring spoons',
 'cream sweetheart mini chest',
 'gold aperitif glass',
 'gold wine glass',
 'gold wine goblet',
 'silver aperitif glass',
 'paper bunting white lace',
 'cream felt easter egg basket',
 "potting shed sow 'n' grow set",
 'potting shed twine',
 'antique silver tea glass etched',
 'paper bunting retro spots',
 'purple sweetheart bracelet',
 'pink sweetheart bracelet',
 'black sweetheart bracelet',
 'green sweetheart bracelet',
 'blue sweetheart bracelet',
 'black diamante expandable ring',
 'amethyst diamante expandable ring',
 'midnight blue pair heart hair slide',
 'crystal pair heart hair slides',
 'rose colour pair heart hair slides',
 'pink enamel+glass hair comb',
 'purple enamel+glass hair comb',
 'diamante bow brooch black colour',
 'pack of 60 pink paisley cake cases',
 '60 teatime fairy cake cases',
 'feltcraft doll molly',
 'set 10 lights night owl',
 'birds mobile vintage design',
 '3 piece jigsaw toadstools',
 'boys alphabet iron on patches',
 'silver cherry lights',
 'girls alphabet iron on patches',
 'red stripe ceramic drawer knob',
 'blue stripe ceramic drawer knob',
 'blue spot ceramic drawer knob',
 'white spot red ceramic drawer knob',
 'white spot blue ceramic drawer knob',
 'blue charlie+lola personal doorsign',
 'red charlie+lola personal doorsign',
 'keep out boys door hanger',
 'toxic area  door hanger',
 'door hanger  mum + dads room',
 'moody boy  door hanger',
 'wooden frame antique white',
 'wood s/3 cabinet ant white finish',
 'wood 2 drawer cabinet white finish',
 'pack of 72 retro spot cake cases',
 'fairy cake candles',
 'ceramic bowl with strawberry design',
 'ceramic cake bowl + hanging cakes',
 '85123a mixed',
 'folding umbrella , black/blue  spot',
 'folding umbrella  pink/white  spot',
 'folding umbrella  cream/multi  spot',
 'folding umbrella , red/white spot',
 'folding umbrella  white/red  spot',
 'piccadilly tea set',
 'retro blue spotty washing up gloves',
 'retro pink spot washing up gloves',
 'funky washing up gloves assorted',
 'door mat fairy cake',
 'fawn blue hot water bottle',
 'antique lily fairy lights',
 'vintage cream 3 basket cake stand',
 'short',
 '21733 mixed',
 'feltcraft 6 flower friends',
 'mushroom blue hot water bottle',
 'chick grey hot water bottle',
 'grey floral feltcraft shoulder bag',
 'pink floral feltcraft shoulder bag',
 'pink crochet cat with scarf',
 'pink cream felt craft trinket box',
 'pink jumper larry the lamb',
 "set of three 50's gift wraps",
 'party invites jazz hearts',
 'party invites woodland',
 'pink 3 piece mini dots cutlery set',
 'blue 3 piece mini dots cutlery set',
 'coffee mug cat + bird design',
 'coffee mug dog + ball design',
 'sweetheart ceramic trinket box',
 'opulent velvet candle in box',
 'vintage rose bead bracelet blue',
 'white glass chunky charm bracelet',
 'black gemstone bracelet',
 'carnival bracelet',
 'jumbo storage bag skulls',
 'dairy maid ceramic butter dish',
 'retro spot large milk jug',
 'kiss reindeer scandinavian stocking',
 'ladybird + bee raffia food cover',
 'tea time party bunting',
 'weekend bag vintage rose paisley',
 'white skull hot water bottle',
 'vintage heads and tails card game',
 'colour glass. star t-light holder',
 'ceramic cake stand + hanging cakes',
 'mini cake stand with hanging cakes',
 'victorian sewing box large',
 'set/3 tall glass candle holder pink',
 "pink fairy cake child's apron",
 'pink union jack  luggage tag',
 'laundry 15c metal sign',
 'airline lounge,metal sign',
 'metal sign cupcake single hook',
 'no junk mail metal sign',
 'pink union jack  passport cover',
 "black sil't squ candle plate",
 'woodland charlotte bag',
 'potting shed coffee mug',
 'pottering mug',
 'fairy soap soap holder',
 'union jack flag passport cover',
 'flower vine raffia food cover',
 'vintage notebook paris days',
 'square mirror curtain',
 'english rose tea set in gift box',
 'green 3 piece mini dots cutlery set',
 'green  spotty plate',
 'green spotty cup',
 'bag 500g swirly marbles',
 'vintage seaside jigsaw puzzles',
 'pink strawberry handbag',
 'glitter star garland with bells',
 'hairclips forties fabric assorted',
 'retro spot small tube matches',
 'jumbo storage bag suki',
 "carousel des child's apron",
 'red 3 piece mini dots cutlery set',
 'set of 2 fancy font tea towels',
 'cross stitch alphabet cushion cover',
 's/4 pistachio lovebird coasters',
 'heart decoration painted zinc',
 'white pearl beaded heart, small',
 'gingham heart decoration',
 'blue  spotty plate',
 'blue spotty bowl',
 'frappucino scarf knitting kit',
 'wash bag vintage rose paisley',
 'green rose washbag',
 'blue/brown dots ruffled umbrella',
 'pink/brown dots ruffled umbrella',
 'aged glass silver t-light holder',
 'silver hanging t-light holder',
 'chocolate this way metal sign',
 'mirrored wall art poppies',
 'hand over the chocolate   sign',
 'painted bird assorted christmas',
 '12 pencils tall tube posy',
 '12 pencils tall tube skulls',
 'large heart flowers hook',
 '2 daisies hair comb',
 'ant white wire heart spiral',
 'green vintage earrings',
 'filigree diamante earrings',
 'pink vintage victorian earrings',
 'brown vintage victorian earrings',
 'silver hoop earrings with flower',
 'raspberry ant copper flower necklac',
 "new baroque b'fly necklace red",
 'flower glass garland neckl.36"black',
 'old rose combo bead necklace',
 'pink/amethyst/gold necklace',
 '5 strand glass necklace crystal',
 'purple current candle ring',
 'white chocolate scent candle',
 'four hook  white lovebirds',
 'door mat new england',
 'door mat green paisley',
 'grand chocolatecandle',
 'set/3 decoupage stacking tins',
 'glitter butterfly clips',
 'ribbon reel spots design',
 'ribbon reel stripes design',
 'shoe shine box',
 'party metal sign',
 'no singing metal sign',
 '12 egg house painted wood',
 'pink heart candy button calculator',
 'paper bunting vintage paisley',
 'silver mini tape measure',
 'assorted santa christmas decoration',
 'noel wooden block letters',
 'zinc metal heart decoration',
 <NA>,
 'yellow red flower piggy bank',
 'colouring pencils brown tube',
 'grey heart hot water bottle',
 'camouflage ear muff headphones',
 'local cafe mug',
 'knitted union flag hot water bottle',
 'blue white scarf hot water bottle',
 'geisha girl chopsticks set/5',
 'urban chic chopsticks set/5',
 'potting shed tea mug',
 'kings choice mug',
 'eight piece dinosaur set',
 'eight piece creepy crawlie set',
 'eight piece snake  set',
 'rattle snake eggs',
 'dinosaur keyrings assorted',
 'assorted tutti frutti notebook',
 'cake stand lace white',
 'cake plate lovebird white',
 'coffee mug pink paisley design',
 'coffee mug blue paisley design',
 'coffee mug pears  design',
 'coffee mug apples design',
 'party cones carnival assorted',
 'antique glass heart decoration',
 'assorted tutti frutti keyring',
 'angel decoration 3 buttons',
 'star decoration rustic',
 'wooden box of dominoes',
 'green christmas tree string 20light',
 'red reindeer string of 20 lights',
 'cosy hour giant tube matches',
 'retro spot giant  tube matches',
 'glitter christmas heart',
 'glitter christmas star',
 'glitter christmas tree',
 'door mat 3 smiley cats',
 'red spotty coir doormat',
 'doormat hearts',
 'skulls wrap',
 'minature coloured gardening set',
 'green blue flower piggy bank',
 'pink spotty bowl',
 'red spotty bowl',
 'set/6 red spotty paper cups',
 'set of 6 cake chopsticks',
 'camouflage led torch',
 'chocolate calculator',
 '200 red + white bendy straws',
 'i can only please one person mug',
 'metal sign empire tea',
 'cook with wine metal sign',
 'gin + tonic diet metal sign',
 'pottering in the shed metal sign',
 'popcorn holder , small',
 'set/6 red spotty paper plates',
 'set/6 christmas icicle t-lights',
 'mirror mosaic t-light holder round',
 'white with black cats mug',
 'painted metal pears assorted',
 'red spotty cup',
 'blue  spotty cup',
 'pink  spotty cup',
 'magic garden mount fuji',
 'magic sheep wool growing from paper',
 '6 ribbons rustic charm',
 'traditional christmas ribbons',
 'scandinavian reds ribbons',
 '6 ribbons elegant christmas',
 '6 ribbons empire',
 'light pink cherry lights',
 'brown flower lights',
 'willow branch lights.',
 'blue pull back racing car',
 'set/6 3d kit cards for kids',
 'pack of 60 mushroom cake cases',
 'red spots  wrap',
 'silver hanging t-light holder dome',
 'retro spots pudding bowl',
 'red spotty shopper bag',
 'loo roll  metal sign',
 'pink juicy fruit photo frame',
 'retro spots butter dish',
 'wrap blizzard',
 'retro spot traditional teapot',
 'retro spot sugar jam bowl',
 'set/5 red spotty lid glass bowls',
 'red spotty plate',
 'jigsaw toadstools 3 piece',
 'retro spot small milk jug',
 'retro spot mug',
 'retro spot storage jar',
 'tea cup and saucer retro spot',
 'edwardian parasol black',
 'edwardian parasol natural',
 'felt toadstool large',
 'felt toadstool  small',
 'polyester filler pad 40x40cm',
 'polyester filler pad 60x40cm',
 'kids rain mac blue',
 'kids rain mac pink',
 'red spotty childs umbrella',
 'zinc willie winkie  candle stick',
 'cream sweetheart magazine rack',
 'door mat topiary',
 'swallows greeting card',
 'set/20 posies paper napkins',
 'blue paisley notebook',
 'blue paisley journal',
 'penny farthing birthday card',
 'vippassport cover',
 'set/10 pink spotty party candles',
 'set/10 blue spotty party candles',
 'tropical luggage tag',
 'wrap, friendship on green',
 'strawberries print bowl',
 'pack 20 english rose paper napkins',
 'tropical passport cover',
 'union jack flag luggage tag',
 'vip luggage tag',
 'chrysanthemum notebook',
 'green fern notebook',
 'robot birthday card',
 'dinosaur birthday card',
 'multi hearts  stickers',
 'skulls  water transfer tattoos',
 'rose du sud childs apron',
 'pink dress jewellery stand',
 'black stitched wall clock',
 'red gingham rose jewellery box',
 'f fairy potpourri cushions lavender',
 'pink spots  wrap',
 'green gingham flower jewellery box',
 'kensington coffee set',
 'ocean scent candle in jewelled box',
 'rose scent candle jewelled drawer',
 'glass honeypot wasp catcher',
 'cosy hour cigar box matches',
 's/4 festive green dinner candles',
 'rex cash+carry jumbo shopper',
 'bright blues ribbons',
 'pack of 12 hearts design tissues',
 'pack of 12 red spotty tissues',
 'recycled pencil with rabbit eraser',
 'rotating silver angels t-light hldr',
 '60 gold and silver fairy cake cases',
 'strawberry scented set/9 t-lights',
 'cinammon set of 9 t-lights',
 'frosted box 9 white t-light candles',
 'small retro spot mug in box  white',
 'small retro spot mug in box  red',
 'asstd design bubble gum ring',
 'romantic pinks ribbons',
 'silver christmas tree bauble stand',
 'corona mexican tray',
 'milk pan red retrospot',
 'silver sleighbell  wreath',
 'dairy maid  pudding bowl',
 'dairy maid large milk jug',
 'french enamel candleholder',
 'joy wooden block letters',
 'woolly hat sock glove advent string',
 'discount',
 'large camphor wood field mushroom',
 'red star card holder',
 'english rose garden secateurs',
 'english rose torch',
 'christmas hanging tree with bell',
 'white dove honeycomb paper garland',
 'set of 12 lily botanical t-lights',
 'pink stripe hot water bottle',
 'set/6 ivory bird t-light candles',
 'set/6 silver reindeer t-lights',
 'set/6 black snowflake t-lights',
 'slate tile natural hanging',
 'rain hat with red spots',
 'wise man star shape egg pan',
 'set 12 kids colour  chalk sticks',
 'feather duster, coal black',
 'crochet bear with blue stripes',
 'small skull windmill',
 '72 round pink doilies',
 'set of 20 kids cookie cutters',
 'black love bird t-light holder',
 'strawberry bath sponge',
 'watermelon bath sponge',
 'sandwich bath sponge',
 "ass col small sand frog p'weight",
 's/6 wooden skittles in cotton bag',
 'set/6 pink bird t-light candles',
 'vanilla incense in tin',
 '12 pencils small tube red spotty',
 '12 mini toadstool pegs',
 'photo cube',
 '3 stripey mice feltcraft',
 'feltcraft butterfly hearts',
 'toast its - fairy flower',
 'toast its - dinosaur',
 'hearts  stickers',
 'woodland  stickers',
 'glass star frosted t-light holder',
 'hi tec alpine hand warmer',
 'love heart pocket warmer',
 'assorted tutti frutti bracelet',
 'traditional wooden catch cup game',
 'queen of skies luggage tag',
 'modern floral stationery set',
 'skull shoulder bag',
 'woodland design  cotton tote bag',
 'lolita  design  cotton tote bag',
 'save the planet cotton tote bag',
 'jumbo bag owls',
 'jumbo bag woodland animals',
 'pop art pen case & pens',
 'dinosaur lunchbox with cutlery',
 'silver finch decoration',
 'black pirate treasure chest',
 'small camphor wood field  mushroom',
 'camphor wood portobello mushroom',
 'porcelain t-light holders assorted',
 'bird box christmas tree decoration',
 'set/6 black glitter reindeer candle',
 'charlotte bag , suki design',
 'skulls  design  cotton tote bag',
 'lunch bag  black skull.',
 'vintage billboard drink me mug',
 'vintage billboard love/hate mug',
 'cream heart card holder',
 'door mat sweet home',
 'door mat welcome puppies',
 'door mat english rose',
 'recipe box with metal heart',
 'red floral feltcraft shoulder bag',
 'green floral feltcraft shoulder bag',
 'set 3 wicker log baskets',
 'yellow purple daisy felt purse kit',
 'yellow flowers felt handbag kit',
 'frying pan union flag',
 'light bird house tree decoration',
 'glitter hanging butterfly string',
 'orange scented set/9 t-lights',
 'brown check cat doorstop',
 '4 ivory dinner candles gold flock',
 'floral folk stationery set',
 'pink heart dots hot water bottle',
 'garland with stars and bells',
 'garland with hearts and bells',
 'red white scarf  hot water bottle',
 'string of 8 butterflies,pink',
 '4 ivory dinner candles silver flock',
 's/4 burgundy wine dinner candles',
 's/4 festive red dinner candles',
 'cake stand victorian filigree med',
 'red hanging metal star tlight hldr',
 'set of kitchen wall  stickers',
 'set/4 pink orchid candles in bowl',
 'set/4 blue flower candles in bowl',
 'funky monkey mug',
 'big doughnut fridge magnets',
 'floral elephant soft toy',
 'sleeping cat erasers',
 'black and white paisley flower mug',
 'greeting card, rita',
 'set/20 red spotty paper napkins',
 'pack of 12 skull tissues',
 'bird house hot water bottle',
 'wire flower t-light holder',
 'assorted fragrance bath confetti',
 'place setting white star',
 'premium church candle',
 'ribbon reel flora + fauna',
 'ribbon reel hearts design',
 'abstract circles pocket book',
 'green fern pocket book',
 'set of 6 girls celebration candles',
 'set 6 football celebration candles',
 'mirror mosaic t-light holder',
 'small folkart christmas tree dec',
 'small folkart star christmas dec',
 'smallfolkart bauble christmas dec',
 'pink heart shape egg frying pan',
 'english rose design peg bag',
 'pink 3 tier glass plate stand',
 'green 3 tier glass plate stand',
 'family album white picture frame',
 'large green peony folding stool',
 'large pink peony folding stool',
 'frying pan blue polkadot',
 'tea time cake stand in gift box',
 'swallow cigar box matches',
 'paper chain kit skulls',
 'jumbo  bag baroque black white',
 'tea bag plate red spotty',
 'white jewelled heart decoration',

In [30]:
import numpy as np

# ORDER MATTERS: np.select uses the first rule that matches
RULES = [
    ("non-product / adjustments",
     r"^(?:postage|discount|short)$|\bmixed$"),

    ("christmas & seasonal decorations",
     r"christmas|xmas|wreath|baubles|santa|reindeer|advent|easter|stocking|gingerbread|sleigh|icicle|snowflake|\bnoel\b|holly|tinsel|tree decoration|angel decoration|folkart.*dec|scandinavian heart dec|woolly hat sock glove"),

    # signs/letters/doorstops early so 'bath', 'chocolate', 'party' in a sign name don't misfile it
    ("home decor & ornaments",
     r"\bsign\b|door hanger|door ?sign|doorstop|blackboard|block word|block letters|wood letters"),

    ("toys & games",
     r"(?<!\bbag )(?<!\blola )\btoys?\b|(?<!russian )\bdolls?\b|teddy|\bgames?\b|puzzle|jigsaw|snakes & ladders|bingo|domino|skittles|skipping|marbles|racing car|helicopter|gliders|rattle|\bmobile\b|monster|eight piece|space frog|treasure chest|snap cards|kit cards|windmill|crocheted animal|crochet (?:bear|cat)|larry the lamb|baby mouse|lamb with pants|stripey mice|magic (?:sheep|garden)"),

    ("party & gift supplies",
     r"\bparty\b|balloons?(?! writing)|bunting|\bwraps?\b|gift (?:wraps?|bags?|tags?)|ribbons?|\bcards?\b(?! holder)|napkins?(?! rings)|paper (?:cups|plates|chain)|doilies|straws|cake cases|mini cases|tissues|tissue ream|honeycomb|(?<!\bbath )confetti|invites"),

    ("stationery & office supplies",
     r"notebook|journal|sketchbook|\bpens?\b|pencils?|bookmark|stationery|notepad|memo|pocket book|writing set|chalk|stickers?|tattoos|erasers?"),

    ("jewellery & hair accessories",
     r"necklac|neckl\.|bracelet|earring|brooch|expandable ring|bubble gum ring|key ?rings?|key fob|hair ?(?:slides?|comb|clips?|band)|\bclips\b|charm\b|jewellery|jewelry"),

    ("bathroom & personal care",
     r"soap|toothbrush|\bbath\b|bathroom|sponge|toilet|wash ?bag|cosmetic bag|shower"),

    ("craft & sewing",
     r"\bkit\b|sewing|knitting|iron on patches|stamp set|feltcraft(?!.*\bbag\b)|glass gems"),

    ("candles, lighting & fragrance",
     r"candl|t-?light|tlight|lantern|lamp|lights?\b|torch|matches|incense|sachet|potpourri|scent"),

    ("textiles & soft furnishings",
     r"cushion|curtain|blanket|\bthrow\b|towel|apron|scarf|c/cover|hot water bottle|hottie|warmer|slipper|door ?mat|flannel|filler pad|gloves?\b"),

    ("kitchenware & dining",
     r"\bmugs?\b|\bcups?\b|saucer|\bplates?\b|\bbowls?\b|cutlery|teapot|tea set|coffee set|breakfast|kitchen|cooking|baking|\bpan\b|frying|\bjugs?\b|butter dish|\bdish\b|toastrack|toast its|cake stand|cake tins?|chopsticks|measuring spoons|\bladle|salad servers|cookie cutters|food (?:cover|container)|lunch ?box|place setting|coasters?|placemats?|napkin rings|aperitif|wine (?:glass|goblet)|milkshake glass|tea glass|chalice|goblet|french enamel|popcorn|\btray\b|utensil|egg cup"),

    ("bags & travel accessories",
     r"(?<!\btea )(?<!\bin )(?<!\bcotton )(?<!\bgauze )bag|purse|wallet|luggage|passport|shopper|\btote\b|\bcases?\b|umbrella|parasol|rain mac|rain hat"),

    ("garden & outdoor",
     r"garden|planter|flower pot|birdhouse|bird feeder|secateurs|potting shed|seed|wasp|twine"),

    ("tools & electronics",
     r"tool set|tape measure|calculator|headphones?|speaker"),

    ("storage & household organization",
     r"storage|\bbox(?:es)?\b|basket|\bjar\b|\btins?\b|hook|trinket|chest|cabinet|\brack\b|shelf|organiser|card holder|\bpegs?\b|duster"),

    ("food & drink",
     r"chocolates?|\bcandy\b|\bsweets\b|marshmallow|\btea\b|coffee|biscuit|licorice|jelly"),

    # explicit home decor keywords (last, so every other rule gets first pick)
    ("home decor & ornaments",
     r"ornament|figurine|frame|wall art|decoration|\bdecs?\b|mirror|clock|garland|ducks|magnet|knob|hanging|heart|dove|bird|piggy bank|globe|disco ball|photo cube|p'weight|mushroom|butterfl|trellis|filigree|hand open shape|wire|zinc|toadstool|egg house|slate|bottle|crochet|felt|wood"),
]

# anything with a description that matches NO rule above
DEFAULT_CATEGORY = "other"

desc = df_all["description"].fillna("").str.lower().str.strip()

conditions = [desc.str.contains(pattern, regex=True) for _, pattern in RULES]
categories = [name for name, _ in RULES]

df_all["category"] = np.select(conditions, categories, default=DEFAULT_CATEGORY)

# only missing/blank descriptions are "unknown"
df_all.loc[desc.eq(""), "category"] = "unknown"

In [31]:
df_all.head()

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales,category
0,489434,85048,15cm christmas glass ball 20 lights,12,2009-12-01 07:45:00,6.95,13085.0,united kingdom,2009,December,Tuesday,7,no,83.4,83.4,christmas & seasonal decorations
1,489434,79323p,pink cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0,"candles, lighting & fragrance"
2,489434,79323w,white cherry lights,12,2009-12-01 07:45:00,6.75,13085.0,united kingdom,2009,December,Tuesday,7,no,81.0,81.0,"candles, lighting & fragrance"
3,489434,22041,"record frame 7"" single size",48,2009-12-01 07:45:00,2.10,13085.0,united kingdom,2009,December,Tuesday,7,no,100.8,100.8,home decor & ornaments
4,489434,21232,strawberry ceramic trinket box,24,2009-12-01 07:45:00,1.25,13085.0,united kingdom,2009,December,Tuesday,7,no,30.0,30.0,storage & household organization

In [32]:
df_all["category"].unique()

<ArrowStringArray>
['christmas & seasonal decorations',    'candles, lighting & fragrance',
           'home decor & ornaments', 'storage & household organization',
             'kitchenware & dining',      'textiles & soft furnishings',
                     'toys & games',            'party & gift supplies',
     'stationery & office supplies',        'bags & travel accessories',
                            'other',        'non-product / adjustments',
                   'craft & sewing',         'bathroom & personal care',
                 'garden & outdoor',     'jewellery & hair accessories',
              'tools & electronics',                          'unknown',
                     'food & drink']
Length: 19, dtype: str

In [40]:
check = df_all.iloc[df_all["category"] == "kitchenware & dining"]
check.head(25)

,invoice,stockcode,description,quantity,invoicedate,price,customerid,country,year,month,day,hour,returned,gross_sales,net_sales,category
6,489434,21871,save the planet mug,24,2009-12-01 07:45:00,1.25,13085.0,united kingdom,2009,December,Tuesday,7,no,30.00,30.00,kitchenware & dining
8,489435,22350,cat bowl,12,2009-12-01 07:46:00,2.55,13085.0,united kingdom,2009,December,Tuesday,7,no,30.60,30.60,kitchenware & dining
9,489435,22349,"dog bowl , chasing ball design",12,2009-12-01 07:46:00,3.75,13085.0,united kingdom,2009,December,Tuesday,7,no,45.00,45.00,kitchenware & dining
10,489435,22195,heart measuring spoons large,24,2009-12-01 07:46:00,1.65,13085.0,united kingdom,2009,December,Tuesday,7,no,39.60,39.60,kitchenware & dining
11,489435,22353,lunchbox with cutlery fairy cakes,12,2009-12-01 07:46:00,2.55,13085.0,united kingdom,2009,December,Tuesday,7,no,30.60,30.60,kitchenware & dining
20,489436,22109,full english breakfast plate,16,2009-12-01 09:06:00,3.39,13078.0,united kingdom,2009,December,Tuesday,9,no,54.24,54.24,kitchenware & dining
21,489436,22107,pizza plate in box,4,2009-12-01 09:06:00,3.75,13078.0,united kingdom,2009,December,Tuesday,9,no,15.00,15.00,kitchenware & dining
28,489436,84596f,small marshmallows pink bowl,8,2009-12-01 09:06:00,1.25,13078.0,united kingdom,2009,December,Tuesday,9,no,10.00,10.00,kitchenware & dining
40,489437,37370,retro coffee mugs assorted,12,2009-12-01 09:08:00,1.25,15362.0,united kingdom,2009,December,Tuesday,9,no,15.00,15.00,kitchenware & dining
65,489438,84519a,tomato charlie+lola coaster set,56,2009-12-01 09:24:00,2.15,18102.0,united kingdom,2009,December,Tuesday,9,no,120.40,120.40,kitchenware & dining
66,489438,84519b,carrot charlie+lola coaster set,60,2009-12-01 09:24:00,2.40,18102.0,united kingdom,2009,December,Tuesday,9,no,144.00,144.00,kitchenware & dining
72,489439,22138,baking set 9 piece retrospot,9,2009-12-01 09:28:00,4.95,12682.0,france,2009,December,Tuesday,9,no,44.55,44.55,kitchenware & dining
73,489439,22139,retro spot tea set ceramic 11 pc,9,2009-12-01 09:28:00,4.95,12682.0,france,2009,December,Tuesday,9,no,44.55,44.55,kitchenware & dining
74,489439,22352,lunchbox with cutlery retrospot,12,2009-12-01 09:28:00,2.55,12682.0,france,2009,December,Tuesday,9,no,30.60,30.60,kitchenware & dining
90,489440,22350,cat bowl,8,2009-12-01 09:43:00,2.55,18087.0,united kingdom,2009,December,Tuesday,9,no,20.40,20.40,kitchenware & dining
91,489440,22349,"dog bowl , chasing ball design",8,2009-12-01 09:43:00,3.75,18087.0,united kingdom,2009,December,Tuesday,9,no,30.00,30.00,kitchenware & dining
93,489441,22138,baking set 9 piece retrospot,6,2009-12-01 09:44:00,4.25,18087.0,united kingdom,2009,December,Tuesday,9,no,25.50,25.50,kitchenware & dining
139,489445,22138,baking set 9 piece retrospot,3,2009-12-01 09:57:00,4.95,17519.0,united kingdom,2009,December,Tuesday,9,no,14.85,14.85,kitchenware & dining
155,489446,22199,frying pan red polkadot,4,2009-12-01 10:06:00,4.25,13758.0,united kingdom,2009,December,Tuesday,10,no,17.00,17.00,kitchenware & dining
170,489446,21217,red spotty round cake tins,12,2009-12-01 10:06:00,8.95,13758.0,united kingdom,2009,December,Tuesday,10,no,107.40,107.40,kitchenware & dining
171,489446,22195,large heart measuring spoons,12,2009-12-01 10:06:00,1.65,13758.0,united kingdom,2009,December,Tuesday,10,no,19.80,19.80,kitchenware & dining
174,489448,20827,gold aperitif glass,48,2009-12-01 10:18:00,2.12,15413.0,united kingdom,2009,December,Tuesday,10,no,101.76,101.76,kitchenware & dining
175,489448,20825,gold wine glass,48,2009-12-01 10:18:00,3.39,15413.0,united kingdom,2009,December,Tuesday,10,no,162.72,162.72,kitchenware & dining
176,489448,20823,gold wine goblet,48,2009-12-01 10:18:00,4.25,15413.0,united kingdom,2009,December,Tuesday,10,no,204.00,204.00,kitchenware & dining
177,489448,20826,silver aperitif glass,48,2009-12-01 10:18:00,2.12,15413.0,united kingdom,2009,December,Tuesday,10,no,101.76,101.76,kitchenware & dining

In [35]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044848 entries, 0 to 1044847
Data columns (total 16 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   invoice      1044848 non-null  string
 1   stockcode    1044848 non-null  string
 2   description  1040573 non-null  string
 3   quantity     1044848 non-null  int64
 4   invoicedate  1044848 non-null  datetime64[us]
 5   price        1044848 non-null  float64
 6   customerid   809561 non-null   float64
 7   country      1044848 non-null  str
 8   year         1044848 non-null  int32
 9   month        1044848 non-null  str
 10  day          1044848 non-null  str
 11  hour         1044848 non-null  int32
 12  returned     1044848 non-null  str
 13  gross_sales  1044848 non-null  float64
 14  net_sales    1044848 non-null  float64
 15  category     1044848 non-null  str
dtypes: datetime64[us](1), float64(4), int32(2), int64(1), str(5), string(3)
memory usage: 209.0 MB

**save as parquet**

In [36]:
df_all.to_parquet("../data/combined_all.parquet")